# Generated by Django 4.2.1 on 2023-05-11 16:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('district_name_ru', models.CharField(db_index=True, max_length=100)),
                ('district_name_en', models.CharField(db_index=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person_name_ru', models.CharField(db_index=True, max_length=100)),
                ('person_name_en', models.CharField(db_index=True, max_length=100)),
                ('birth_date', models.IntegerField()),
                ('death_date', models.IntegerField()),
                ('content', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Street',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street_name_ru', models.CharField(db_index=True, max_length=100)),
                ('street_name_en', models.CharField(db_index=True, max_length=100)),
                ('coordinates_0', models.FloatField()),
                ('coordinates_1', models.FloatField()),
                ('id_district', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='streets.district')),
                ('id_person', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='streets.person')),
            ],
        ),
    ]
