# Generated by Django 4.2.1 on 2023-05-25 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streets', '0002_person_photo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='content',
            new_name='content_ru',
        ),
        migrations.AddField(
            model_name='person',
            name='content_en',
            field=models.TextField(null=True),
        ),
    ]
