# Generated by Django 4.2.1 on 2023-05-29 06:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('streets', '0003_rename_content_person_content_ru_person_content_en'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='content_en',
            field=models.TextField(default='no_content'),
        ),
        migrations.AlterField(
            model_name='person',
            name='photo',
            field=models.ImageField(upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='street',
            name='id_district',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='streets.district'),
        ),
        migrations.AlterField(
            model_name='street',
            name='id_person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='streets.person'),
        ),
    ]
